vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/userPhotos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        film:
            uri_prefix: /images/film
            upload_destination: '%kernel.project_dir%/public/filmPhotos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer